server:
  port: 0
spring:
  application:
    name: demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka,http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
