server:
  port: 8093
spring:
  application:
    name: demo3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka,http://localhost1:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
